[package]
name = "PrimesRust"
version = "0.1.0"
authors = ["Tamer Bouz El-Jedi <tbejtf@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
bitvec = "*"